<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <?php
$form = $this->form;
$form->get('title')->setAttribute('class', 'form-control');
$form->get('artist')->setAttribute('class', 'form-control');
$form->setAttribute('action', $this->url(
    'album',
    array(
        'action' => 'edit',
        'id' => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo "<br>";
echo $this->formRow($form->get('artist'));
echo "<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
